### ISSUE TITLE
unable to login on fresh installation

### ISSUE THREAD

**Issue by kmwoley** [MiGoller/docker-shinobi#3]
Fresh installation using this docker image.
Navigate to http://host:8080/super
Using `admin@shinobi.video` as username and `admin` as password does not allow me to login.

Running on unraid, so there could be something in how it sets up docker that's unique to my setup causing the issue.

Thanks for your work on this docker.

**Comment by MiGoller** [comment]
Hi kmwoley. 

Thank you for your feedback. Unfortunately I do not have access to any unraid system, neither to any testing appliances. I'll give it a try anyway. How do you start the Shinobi containers? Du you start them by docker run command, or do you use docker-compose? I'm not sure how unraid will do this. I recommend the debian based image for testing.

In both szenarios the default password of the Super-user account should be "administrator" (see the Shinobi.env file for further details, please). Just give a try with this default password, please. If you set the  environment variable ADMIN_USER or ADMIN_PASSWORD to different values you will have to use that values instead, right?.

Let me know if that will work, please.

Regards,
Michael

**Comment by kmwoley** [comment]
Closing this issue - I was indeed using the wrong password. Thanks.

**Comment by MiGoller** [comment]
Hey kmwoley. You are welcome. Enjoy.
