### ISSUE TITLE
Can use " Add Camera" , but it doesn't work

### ISSUE THREAD

**Issue by ysw0421** [MiGoller/docker-shinobi#5]
Hellow, I use your docker images. I wan't to use "add Camera" API for automatic. 
![image](https://user-images.githubusercontent.com/29770142/53727386-7389f580-3eb3-11e9-8f4a-2b49f781314f.png)
I test many thing but not work;
and result is  i can push camera in Shinboi
![image](https://user-images.githubusercontent.com/29770142/53727344-5523fa00-3eb3-11e9-911d-2534fa1ab7f4.png)
but camera not work
but not work how can i do?
help me!
![image](https://user-images.githubusercontent.com/29770142/53727520-cb286100-3eb3-11e9-9de3-b08f11910ea5.png)
![image](https://user-images.githubusercontent.com/29770142/53727504-c06dcc00-3eb3-11e9-841f-ab9d8b1f0231.png)
can you show me success example??

**Comment by MiGoller** [comment]
Hey ysw0421. Thank you for your feedback. 

I've never tried that way to add an camera. Do you run your piece of code on the same machine, vm or container Shinobi is running on? I'm wondering about your cam-url. 

Can you tell me what image type you're running? I need the image's tag or the pull command.

Regards,
Michael

**Comment by ysw0421** [comment]
Hi, Michael

Please save me.
I did the command like this. "docker pull migoller / shinobi: debian" and "RUN Command" as follows: "docker run -d \
     -p 8080: 8080 \
     -v / etc / localtime: / etc / localtime: ro \
     -v / etc / timezone: / etc / timezone: ro \
     -v ~ / Shinobi / config: / config \
     -v ~ / Shinobi / datadir: / var / lib / mysql \
     -v ~ / Shinobi / videos: / opt / shinobi / videos \
     -v / dev / shm / shinobiDockerTemp: / dev / shm / streams \
     migoller / shinobidocker: debian "
And my "RTSP URL" is as follows. "rtsp: //admin@168.131.148.45: 18888 / videoMain"
And I'm running "Ubuntu 16.04 Server".
![image](https://user-images.githubusercontent.com/29770142/53854465-ea86d180-400c-11e9-9a47-9464a593b1fa.png)
I sent both post and get methods. But it did not succeed.
And I want to show you how I send it. So I attach the following zip file.

I got JSON when I would be adding a camera on the web. I then sent it back via api but it did not apply.

[Testing.zip](https://github.com/MiGoller/docker-shinobi/files/2934174/Testing.zip)



Regards,
Sungung

**Comment by ysw0421** [comment]
Maybe I can not hear the answer to this question?

**Comment by MiGoller** [comment]
Hmm... I'm not a node.js dev but that should do the job. My images are based on the master branch of the Shinobi repo. As far as I know there are a lot of changes to the dev branches. 

I'd like you to ask this question on Shinobi's General Support Discord Server. You'll find the invitation on https://shinobi.video/support .

Hope they can answer you that question.

**Comment by MiGoller** [comment]
Ah... btw. hopefully you've changed your passwords. There are some plaintext passwords in you js-code.

**Comment by MiGoller** [comment]
Still have no feedback. Closing the issue.

**Comment by ysw0421** [comment]
Yes sir   please  close  the  issue
Thanks  for  your  help

2019년 7월 23일 (화) 오전 3:09, Skunkworx <notifications@github.com>님이 작성:
